-- Close junk work items (Run STEP1 first to preview!)
UPDATE work_items
SET
  closed_at = NOW(),
  status = 'cancelled'
WHERE closed_at IS NULL
  AND (
    reason_included->>'detected_via' = 'backfill_script'
    OR reason_included->>'detected_via' = 'auto_lead_primary_category'
  )
  AND customer_email NOT ILIKE '%powerfulform.com%'
  AND customer_email NOT ILIKE '%forms-noreply@google.com%'
  AND (
    customer_email ILIKE '%paypal%'
    OR customer_name ILIKE '%paypal%'
    OR customer_email ILIKE '%stripe%'
    OR customer_email ILIKE '%square%'
    OR customer_email ILIKE '%shopify.com%'
    OR customer_email ILIKE '%etsy.com%'
    OR customer_email ILIKE '%amazon.com%'
    OR customer_name ILIKE 'Amazon Services'
    OR customer_email ILIKE '%topdisplay.net%'
    OR customer_email ILIKE '%qing-yulan.com%'
    OR customer_email ILIKE '%uline.com%'
    OR customer_email ILIKE '%trademarkengine.com%'
    OR customer_email ILIKE '%@fraudalert.%'
    OR customer_email ILIKE '%@mail.instagram.com%'
    OR customer_email ILIKE 'security@%'
    OR customer_email ILIKE '%noreply@shopify%'
    OR customer_email ILIKE '%noreply@amazon%'
    OR customer_email ILIKE '%noreply@etsy%'
    OR customer_email ILIKE '%donotreply@amazon%'
    OR customer_email ILIKE '%@notifications.%'
    OR customer_email ILIKE '%@alerts.%'
    OR customer_email ILIKE '%@marketing.%'
    OR customer_email ILIKE '%quickbooks%'
    OR customer_email ILIKE '%intuit%'
    OR customer_email ILIKE '%asana%'
    OR customer_email ILIKE '%trello%'
    OR customer_email ILIKE '%slack%'
    OR customer_email ILIKE '%monday.com%'
    OR customer_email ILIKE '%zoom.us%'
    OR customer_email ILIKE '%adobe%'
    OR customer_email ILIKE '%docusign%'
    OR customer_email ILIKE '%dropbox%'
    OR customer_email ILIKE '%mailchimp%'
    OR customer_email ILIKE '%constantcontact%'
    OR customer_email ILIKE '%sendgrid%'
    OR customer_email ILIKE '%hubspot%'
    OR customer_name ILIKE '%SHOPIFY PRO%'
    OR title ILIKE '%payment confirmation%'
    OR title ILIKE '%order confirmation%'
    OR title ILIKE '%you sent%payment%'
    OR title ILIKE '%you have a payment%'
    OR title ILIKE '%funds%on the way%'
    OR title ILIKE '%trademark monitoring%'
    OR title ILIKE 'Walmart.com:%'
  );
